// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6cGM9Mf2v7Cnqmm4MlSbCbkn2j0I974',
    appId: '1:948284952873:web:c66f2a4ae6103eb1a2e738',
    messagingSenderId: '948284952873',
    projectId: 'app-unicv-ca307',
    authDomain: 'app-unicv-ca307.firebaseapp.com',
    storageBucket: 'app-unicv-ca307.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZTtc7zS6Cj3Fc7nEHFa_Lm6F0nW6PZ0',
    appId: '1:948284952873:android:87bb6b8bf87ac93ea2e738',
    messagingSenderId: '948284952873',
    projectId: 'app-unicv-ca307',
    storageBucket: 'app-unicv-ca307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDK_Xn_aSAu48mTRN0_LDonJyfdcGUSDc',
    appId: '1:948284952873:ios:f8255e8cfdfb304ba2e738',
    messagingSenderId: '948284952873',
    projectId: 'app-unicv-ca307',
    storageBucket: 'app-unicv-ca307.appspot.com',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDK_Xn_aSAu48mTRN0_LDonJyfdcGUSDc',
    appId: '1:948284952873:ios:f8255e8cfdfb304ba2e738',
    messagingSenderId: '948284952873',
    projectId: 'app-unicv-ca307',
    storageBucket: 'app-unicv-ca307.appspot.com',
    iosBundleId: 'com.example.telaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy6cGM9Mf2v7Cnqmm4MlSbCbkn2j0I974',
    appId: '1:948284952873:web:47b7580ea505c7b6a2e738',
    messagingSenderId: '948284952873',
    projectId: 'app-unicv-ca307',
    authDomain: 'app-unicv-ca307.firebaseapp.com',
    storageBucket: 'app-unicv-ca307.appspot.com',
  );
}
